### ISSUE TITLE
Suggestion: something like TemplateLoader from JMustache

### ISSUE THREAD

**Issue by jskov** [jstachio/jstachio#1]
Hi

I have converted one of the templates in my jaxrs generator. It has found a number of fields I did not provide data for, so it has been most excellent to get "static" typing templates. Thanks!

The only feedback I have for now is that maybe you should consider/explore adding something like a TemplateLoader argument to @JStache.

I had to change most of my template files to include the path of partials inclusion, and fix their names.
Not a big issue for me, as I only have one set of templates.

But something like https://github.com/OpenAPITools/openapi-generator would be hard pressed to use jstachio (without big changes), because they rely on folder-namespacing to control load location for partials. 

It might be worth considering to help some projects adopt jstacio (should they want to).

I will convert my remaining templates and let you know if I find any problems (or other suggestions).

Cheers!

**Comment by agentgt** [comment]
There is a `@TemplateBasePath` as well as `@PartialMapping`.

However it isn't as flexible as something programmatic. The issue with something programmatic is it will have to run during compilation and thus I will need something like the ServiceLoader to go load the users `TemplateLoader`.

Ultimately I think we will have to do it anyway as there numerous issues with using the annotation processors `Filer` with various incremental compilers as you noted in #2

**Comment by agentgt** [comment]
Sorry for the annotations I mean `@JStacheBasePath` and `@JStachePartialMapping`.

**Comment by agentgt** [comment]
Ok so I cleaned up the path lookup and all you have to do is (using your project) put

```java
@io.jstach.annotation.JStachePath(prefix = "templates/", suffix = ".mustache")
```
in

`dk.mada.jaxrs.generator.api.tmpl.package-info.java`
 
Assuming you want to use the original layout. (however I noticed there were several templates with partials sometimes having `.mustache` on the end and sometimes not... so probably need to fix that but best to be consistent anyway).

**Comment by jskov** [comment]
So nice! I will give it a spin.
Thanks!

**Comment by jskov** [comment]
Works just fine!
