### ISSUE TITLE
DI Framework support like Spring

### ISSUE THREAD

**Issue by agentgt** [jstachio/jstachio#10]

**Comment by agentgt** [comment]
JStachioServiceContainer to JStachioService.

**Comment by dsyer** [comment]
Looks interesting. I think I'd like to see support for non-blocking I/O (i.e. Webflux) as well: it would mean more work to generate a `*View` class that had non-blocking I/O.

I'm having soine issues trying it out though because I can't build the project. Is `mvn install` at the root generally not the best place to start? Something in the README might be useful?

**Comment by agentgt** [comment]
> Is mvn install at the root generally not the best place to start?

Yes. The project tries to be extremely canonical but perhaps because of all the refactoring you might need to do `mvn clean install` intead of just `mvn install`.

There is a possibility if you try to run the build while your IDE is running you could have problems. This is because the build will reformat (spring format code maven plugin) on compile... I think the default is just verify but I made it do it automatically on build. So I have noticed some times weird behavior with VS Code and sometimes Eclipse where the reformat kicks the incremental compiler into a loop.

> Looks interesting. I think I'd like to see support for non-blocking I/O (i.e. Webflux) as well: it would mean more work to generate a *View class that had non-blocking I/O.

I looked into this awhile ago and unless you have a massive response (rendered template) buffering the response as a string (as in eagerly creating the response body) will be as faster as actually chunkifying the template writing into reactive stream / jdk 9 flow on each `request(1)` which btw most subscribers will just `request(Long.MAX_LONG)`. Then it begs the question of how big the chunks should be (probably configurable) and what they should be (probably bytebuffer).

So what that means is what ever reactive stream implementation you use you would just have a mapping step. 

```
return Mono.of(someModelMono).map(SomeModelRenderer::execute);
```
(I don't know reactor well so the above is probably wrong but I think you get the idea).


That being said I could see how it is reasonable wanting this

```java
@RequestMapping("...")
@ResponseBody
Mono<SomeModel> someModelGet()
```

to work and it might... I just assumed the MessageConverter would handle parameterized Mono/Flux. Maybe it doesn't. I should create a project and test it out!

**Comment by agentgt** [comment]
I guess what I'm saying for reactive is that largely doing:

`Mono<Model> -> (execute(model) -> Mono<String>` where the transition to string is to simply run the renderer eager via reactive map operation is good enough. 

The only case where it would be better to generate code specific to reactive streams is to handle models that have variables aka methods that return Publishers (and friends like Mono, Flux etc). I don't think that is a common use case but then again Mustache.java does something like this but for regularly Futures (e.g. blocking async).

**Comment by dsyer** [comment]
If it's good enough to just use `@ResponseBody` and `String` with reactive, it should be good enough for servlets as well though? So maybe you don't need the `Writer` at all in the `*View` generated classes?

I'd also be happy with your suggestion of using `Mono<SomeModel>` - we'd have to check that the message converter gets used because I vaguely remember there's a different extension point for WebFlux. 

I can't try it until I can build it

> There is a possibility if you try to run the build while your IDE is running you could have problems. 

I believe that is probably the issue. It's a bit of a downer really because it seems like it's a problem that will plague user application code as well. I've never found that APT processors play nicely with IDEs and the problems always seem to come down to this kind of thing.

**Comment by dsyer** [comment]
I made it work by shutting down the IDE (which doesn't work in Codespaces) and building on the command line. It's kind of annoying not to be able to use an IDE I have to say.

Anyway the vanilla `@GetMapping` seems to be rendering JSON (Spring Boot default for a `@ResponseBody` if it doesn't have any other information), so the message converter is not even working for me in MVC. It might be an ordering issue. I'm finding it a bit hard to debug without an IDE.

**Comment by agentgt** [comment]
> I made it work by shutting down the IDE (which doesn't work in Codespaces) and building on the command line. It's kind of annoying not to be able to use an IDE I have to say.

I will make the build no longer reformat so it stops trigger auto builds. For now you can disable that with `-Dformat.validate=true`.

However I want to make sure of something. The build issues are with building JStachio right and not some project that depends on it? For now you can just use the released v0.8.0 in an example project if you are having trouble building it.

> Anyway the vanilla @GetMapping seems to be rendering JSON (Spring Boot default for a @ResponseBody if it doesn't have any other information), so the message converter is not even working for me in MVC. It might be an ordering issue. I'm finding it a bit hard to debug without an IDE.

Yes that is because you have to currently configure the MessageConverter manually as the Jackson one is automatic (see https://github.com/jstachio/jstachio/blob/7f8bbd49fa614ef643aa902a96d4f9d0dc09e794/opt/jstachio-spring-example/src/main/java/io/jstach/opt/spring/example/WebConfig.java#L36). That is probably what I need to do with JStachio is make I guess what Spring Boot calls an actuator or something. That is you can't just put in the JStachio jars in the project like you can with Jackson and expect it to work OOB.

**Comment by dsyer** [comment]
> For now you can disable that with -Dformat.validate=true.

I think it's possible you meant `-Dformat.validate=false`? That seems to work better at least.

**Comment by agentgt** [comment]
Which IDE are you using?

I have noticed there are still lots of issues with modularizing Spring applications and a lot of IDEs seem to still mess up modules. I bet if you move the module-info annotations to a package-info and then blow away the module-info it might work.

I didn't make the build put in a MANIFEST entry for the App.class as I was going to put in the Spring Boot maven plugin but ran out of time.

This all is extremely helpful btw!

**Comment by dsyer** [comment]
> Which IDE are you using?

VSCode. Which would be the same as Eclipse I suspect (same language server).

> I bet if you move the module-info annotations to a package-info and then blow aw>y the module-info it might work.

Yes that works, thank you. It's a bit more complicated than that because there are some javadoc errors in other places once the `module-info.java` is blown away, but the gist is correct.

I debugged the request to the simple `@GetMapping` and it is partly an ordering problem. If the request has no `Accept` header then `application/json` gets preference because Jackson is ordered higher than the custom converter. In a browser it works as you expect, but using `curl` (or similar) you can easily get the wrong result.

**Comment by dsyer** [comment]
VSCode doesn't use the project directory for `.classpath` and `.project` any more, so I don't think that precise procedure will work. They are generated by the same code though, so it should work, once they are properly refreshed.

**Comment by agentgt** [comment]
Yes regardless of the formatting I have noticed issues with VSCode and annotation processing. What made it stop for a little while was loading it up with Eclipse first even recently albeit you are right that I don't think it touches the eclipse settings anymore.

I do use VSCode and all the IDEs frequently because all of them have issues with annotation processing at times (well I'm not sure about netbeans but otherwise they all have issues).

I think it is something to do with its file watcher and running the build on the command line with VSCode. The command line triggers a build in vs code because its file watcher is very very fast so basically you have two builds running at the same time and ultimately I think this is the issue.

Its like the annotation processor generates code and VSCode

**Comment by dsyer** [comment]
So with the "remove module-info.java" trick I was able to try the sample out properly and I can see that using `@ResponseBody` with a `String` return value works fine with MVC. It won't work with Webflux though because the `HttpMessageConverter` is an MVC extension point (as I suspected). We could add an `HttpMessageWriter` and register that instead. But it's going to mess with your neat modules - you will need a new module for WebFlux, so in the end `jstachio-spring` would end up being 3 different modules (a base, non web version, an MVC version and a WebFlux version). The way we deal with this kind of combinatoric explosion in Spring Boot is to ignore modules and make the extra dependencies optional, then pick an implementation at runtime. It's your choice, but I can't think of another way to make it work.

Also, regarding modules and module paths, I see there are no tests in the sample project. As soon as you add a test the IDEs are going to flip out and stop working, right (the test dependencies won't be in the module path)? It's not a problem I've had to solve before - I guess I always just use the classpath.

**Comment by dsyer** [comment]
FWIW the sample works with this (registered in a `WebFluxConfigurer` instead of a `WebMvcConfigurer`):

```java
class JStachioHttpMessageWriter extends AbstractSingleValueEncoder<Object> {

	private final JStachio jstachio;

	public JStachioHttpMessageWriter(JStachio jstachio) {
		super(MediaType.TEXT_HTML);
		this.jstachio = jstachio;
	}

	@Override
	public boolean canEncode(ResolvableType elementType, @Nullable MimeType mimeType) {
		Class<?> clazz = elementType.toClass();
		return clazz != Object.class && !CharSequence.class.isAssignableFrom(clazz) && jstachio.supportsType(clazz);
	}

	@Override
	protected Flux<DataBuffer> encode(Object event, DataBufferFactory bufferFactory, ResolvableType type,
			@Nullable MimeType mimeType, @Nullable Map<String, Object> hints) {
		return Flux.just(encodeValue(event, bufferFactory, type, mimeType, hints));
	}

	@Override
	public DataBuffer encodeValue(Object event, DataBufferFactory bufferFactory, ResolvableType valueType,
			MimeType mimeType, Map<String, Object> hints) {
		if (logger.isDebugEnabled() && !Hints.isLoggingSuppressed(hints)) {
			String logPrefix = Hints.getLogPrefix(hints);
			logger.debug(logPrefix + "Writing [" + event + "]");
		}
		
		Charset charset = StandardCharsets.UTF_8;
		return bufferFactory.wrap(jstachio.execute(event).getBytes(charset));
	}

}
```

**Comment by agentgt** [comment]
> So with the "remove module-info.java" trick I was able to try the sample out properly and I can see that using @ResponseBody with a String return value works fine with MVC. The other endpoint won't work with Webflux though because the HttpMessageConverter is an MVC extension point (as I suspected). We could add an HttpMessageWriter and register that instead. But it's going to mess with your neat modules - you will need a new module for WebFlux, so in the end jstachio-spring would end up being 3 different modules (a base, non web version, an MVC version and a WebFlux version). The way we deal with this kind of combinatoric explosion in Spring Boot is to ignore modules and make the extra dependencies optional, then pick an implementation at runtime. It's your choice, but I can't think of another way to make it work.

Yes I agree everything above and had similar thoughts as well. If it wasn't Spring I would make three modules but given the desire for Spring users these days (which are mostly boot users) for easiness makes multiple modules less desirable.

Ultimately Spring still is just not geared for modularization yet. The spring modules are essentially all opt-in as in if they did have a `module-info` (which they do not but rather Automatic-Module) it would all be `require static`. That is if you require say spring web module you have to go off and require all dependencies as well as there is no transitive association.

> Also, regarding modules and module paths, I see there are no tests in the sample project. As soon as you add a test the IDEs are going to flip out and stop working, right (the test dependencies won't be in the module path)? It's not a problem I've had to solve before - I guess I always just use the classpath.

This used to be a problem but both Maven, Eclipse, and I believe Intellij do some magic now such that `src/test/java` becomes its own fake module which as complete access to `src/main/java` as well as adds reflective access (`open`) to junit (I'm probably getting some of the details wrong but roughly that is how it works).

There are some edge cases where it doesn't work though that I can't recall having to do with Junit 5 (and is one of the reasons why this project uses junit 4).

The webflux stuff looks great and I will try to incorporate it soon. 

I thought about it last night and I think version 2.0 some time next year I will try to tackle generating reactive code but right now its massive work to make the code generator build a giant monad. Plus I was hoping to just use the JDK Flow support (aka reactive streams that is builtin 9) but lacks implementations and operators and thus I would have to basically implement my own micro implementation. Instead it probably is easier and more efficient to generate code for each major reactive library: (reactor, rxjava, small rye). Another combinatorics explosion.

**Comment by dsyer** [comment]
Some good news: the Spring sample compiles to a native image with GraalVM with no changes other than the build configuration. At some point it might make sense to use `spring-boot-starter-parent` as a parent pom somewhere in the chain for the sample to make that easier. In the meantime you can follow instructions in the Spring Boot user guide, or just copy paste from the starter parent anything with the word "native" in it.

**Comment by agentgt** [comment]
I also added another way to use JStachio and Spring MVC (stress the MVC part).

I will add the webflux part soon. I'm wondering how to make all these different options consumable and easy to understand or what is the best default to ship with for a spring boot starter.

**Comment by agentgt** [comment]
We could just make a static method on 

```java
public static View JStachioModelView.of(Object o) {
}
```

So now only your controllers are coupled.

One could also (not yet though) through JStacheInterfaces make the generated code implement an interface

```java
public interface ViewFactory<T> {
   default View view(T model) {
       //Use JStachioModelView
   }
}
```

On some package:

```java
@JStacheInterfaces(templateImplements=ViewFactory.class)
```

Then in your controller:

```
@Autowired ViewFactory<HelloWorldModel> view;

public View hello() {
   view.view(new HelloWorldModel("view factory example"));
}
```

I forgot how damn powerful spring is. 

Right now `JStacheInterfaces` does not know about parameterization on interfaces but that would be easy to add where we just assume the parameter should be the model.

**Comment by dsyer** [comment]
I like the `@Autowired ViewFactory<HelloWorldModel> view` pattern.

**Comment by dsyer** [comment]
But, looking at the `View` implementation, I can't find a way to like that as much. It throws away the model passed in by Spring which seems counterintuitive. I understand why it looks like that - the model is weakly typed and you can't analyse it at compile time to make it non-reflective - but I think we either have to deal with that (custom `ContextNode` or something?) or ditch the `View` altogether.

P.S. if there's a better place to discuss than this long, long issue thread, let me know.

**Comment by dsyer** [comment]
> My personal choice for non reactive is still the Http message converter option at the moment.

Agree. There's no need for a `Writer` to be injected though is there, really? I'm not sure I see the benefit of that yet, unless there's some streaming option that I'm not seeing yet.

I tried writing a `ViewResolver` and gave up because I couldn't see how the MVC `Model` would ever be used - it's opaque at compile time so you can't build a strongly typed context access, which causes JStache to fall over at the first sign of trouble. If you only use it to pull out a `@JStache` model that defeats the object somewhat. One idea I've thought about a bit is to let the `@JStache` model consume the MVC `Model` somehow, and expose the bits it cares about in a strongly typed way. You don't need a `ViewResolver` for that, though, so I'm not sure I gained anything if I have one. I saw the idea of mixins in the examples here, so it's possible that can be folded in somehow - what you need is some "common behaviour" (e.g. `CsrfToken`, binding errors) that layers on top of the domain concepts in a typical POJO model. I don't know.

**Comment by dsyer** [comment]
I remembered, after trying to use Jstache for an actual HTML we app, that `ViewResolvers` often do nice things to enhance the `Model`. E.g. if Spring Security is in use you get a request attribute called `_csrf` with a `CsrfToken` value and the commonly used `ViewResolvers` will copy that into the model for you. With a weakly typed MVC `Model` that's trivial, but with a strongly typed `@JStache` model it's more of a challenge. The approach I have adopted is to keep the domain POJO simple and unaware of web concerns, and use it as a component in a `@JStacheModel` that is aware of them. E.g.

```java
class Foo {
	private String value = "";

	public Foo() {
	}

	public Foo(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}

@JStache(path = "templates/index.mustache")
@JStachePartials(@JStachePartial(name = "layout", path = "templates/layout.mustache"))
record IndexPage(Application application, Foo foo, BindingResult status, CsrfToken _csrf) {

	public Form form() {
		return new Form("foo", foo, _csrf);
	}

	public InputField field() {
		return new InputField("Value", "value", foo.getValue(), "text", status);
	}

	public List<Menu> getMenus() {
		return application.getMenus();
	}

}
```

then in a `@Controller` I need to do something like this:

```java
@RestController
@RequestMapping("/")
class HomeController {

	private final Application application;

	public HomeController(Application application) {
		this.application = application;
	}

	@GetMapping
	public IndexPage home(@ModelAttribute Foo foo, @RequestAttribute("_csrf") CsrfToken _csrf) {
		return new IndexPage(application, foo, null, _csrf);
	}

	@PostMapping
	public IndexPage post(@ModelAttribute Foo foo, @RequestAttribute("_csrf") CsrfToken _csrf, BindingResult status) {
		return new IndexPage(application, foo, status, _csrf);
	}

}
```
 I'm not sure I like it yet, but it might jog some other ideas, and I know it works.

**Comment by agentgt** [comment]
In my company where we sometimes use Spring and some times do not use a standard `ThreadLocal` service locator like pattern.

You just have a servlet filter or some analog (advisor, interceptor) bind the CSRF to the ThreadLocal.

```java
public interface CsrfSupport {
    default String getCsrf() {
        return CsrfManager.getInstance().csrf();
    }
}

Make all models implement some interface

```java
@JStacheInterface(modelImplements = CsrfSupport.class) // require models implement some interface
package /* or module */ some.pack;
```

Model:

```java
public record SomeModel() implements CsrfSupport {}
```

Yes threadlocals and pseudo singletons are kind of bad but IIRC Spring has some sort of standard way of dealing with this similar to how transactions are dealt with. Something called "Holder". I will look later.

Otherwise yeah we need mutable setters that then will inject stuff into the model.

I'm starting to wonder if maybe the generated template code (instead of the model) is instantiated for every request and injected with data that is only available to the mustache template and the model knows nothing of it.

Basically I'm thinking of adding a special interface (and code generation) that extends the current `Template<Model>` interface:

```java
public MvcTemplate<T> extends Template<T> {
    default void execute(T model, Appendable a, Map<String, Object> attributes) {
        execute(model, a, ContextNode.of(attributes);
    }
    void execute(T model, Appendable a, ContextNode attributes);
}
```

Then `attributes` has to be treated differently for formatting types as the compiler sees it all as Object so we use `ContextNode` which bypasses the formatter types for the most part (I think).

Come to think of it I might just add the above to `Template` aka `JStacheType.JSTACHIO` anyway instead of having a third code generation type (see JStacheType). We could probably make the specially "attributes" field name (not actually a field on the model but the mustache template thinks it is) configurable.

Of course you loose type safety with attributes but maybe for consumption of people used to Map models it is worth it and it provides a migration path for them to go full type safe models.

**Comment by agentgt** [comment]
You can get what I mentioned previously now provided you don't mind making your models mutable.

```
public MvcTemplate<T extends AttributesHolder> extends Template<T> {
    default void execute(T model, Appendable a, Map<String, Object> attributes) {
        execute(model, a, ContextNode.of(attributes);
    }
    void execute(T model, Appendable a, ContextNode attributes) {
        model.setAttributes(attributes);
        // regular execute call;
    }
}

public interfaces AttributesHolder {
    public ContextNode getAttributes();
    public void setAttributes(ContextNode attributes);
}
```

But the above is kind of nasty particularly if want to use Records for models (since you can't use inheritance and records are supposed to be immutable).

**Comment by dsyer** [comment]
So you have to tell JStache to generate instances of `MvcTemplate`? How do you do that?

**Comment by agentgt** [comment]
Ah yeah I made some accidental jumps of logic. You would need a custom JStachio to `instanceof` on it to call it correctly. I'll play with something in a bit and check it in.

**Comment by agentgt** [comment]
Yeah I tried the ViewResolver and I can now clearly see what you are talking about. Like no real gain. I am not sure why I thought it would be better.

I think you have the right idea with some kind of Model container that is aware of the web stuff however I can see a pain point of making a Model Container for every model painful.

I guess the question is should we provide some out of the box interception and injection of models (e.g. to put request attributes on model)?

**Comment by dsyer** [comment]
I tried something a bit different here: https://github.com/dsyer/mustache-sample/tree/jstache. I'm not 100% happy, but it works and the cross-cutting concerns are all centralized in a base model (`BasePage`) and a `View` implementation. I'd be happier if I didn't need one or the other of those, so feedback is welcome.

The good news (for me) is that the app compiles to native with GraalVM and runs cleanly with no additional configuration.

**Comment by agentgt** [comment]
@dsyer I think we have mostly good enough Spring integration. I have updated your Webflux code in 1.0.0 to take advantage of pre-encoding and leverage webflux buffer factory.

Ideally we would have a Spring Boot Autoconfig but that is a separate issue and I'm not sure if it is even really possible given how much JStachio relies on static configuration.

Thanks for all the hard work.

P.S. I'm looking into making the CSRF like issue easier for 2.0.0 #168

**Comment by dsyer** [comment]
I should think autoconfig is possible (open a new issue?). We should do it IMO, but still pleased with the progress so far.
