### ISSUE TITLE
Generate encoded bytes for static parts of templates

### ISSUE THREAD

**Issue by agentgt** [jstachio/jstachio#126]
JStachio currently creates static strings for parts of the templates that are not variables (e.g. content usually markup).

This is generally very fast for writing out ASCII-like text (e.g. 255 and below aka most of latin1). 
The conversion of String to bytes appears to be pretty fast for most cases.

However it is not fast when writing UTF-8 with characters that are not ASCII as those characters need to be encoded.

The only templating engine I know that does pre-encoding is Rocker (and possibly JTE).
This is currently why Rocker appears to run slightly faster on the Tech Empower Fortunes test than JStachio as normally JStachio is faster for ASCII-like text.

https://github.com/jooby-project/jooby/issues/2864

Luckily this is just requires calling `"<html>...".getBytes(UTF-8)` on the string literals and storing them as static fields.

Unfortunately we rely on `Appendable` which doesn't expose appending bytes. Thus we will need to make some API changes. 

We maybe able to wait on actual implementation but at least modify the API.

**Comment by agentgt** [comment]
I kind of knew this would eventually be a problem and is why JStacheContentType has charset.

**Comment by agentgt** [comment]
It is unclear if this is even worth doing. On isolated benchmarks like the template-benchmark it is not faster at all and is probably why Rocker runs slower than JTE and JStachio as the test tests toString and not `byte[]`. However even naively converting the whole template to `byte[]` with `String.getBytes` appears to be faster than having the parts of the template pre-encoded.

The only time I saw pre-encoding run faster was in Techempower and threadlocal buffers were in play. This was the only time I saw Rocker *sometimes* slightly outperform JStachio (when not doing pre-encoding which is the current default behavior).


With the template-benchmark that uses JMH to test pre-encoding was much slower.

I'll have to wait to see what @jknack decides on how to design the new Jooby `MessageEncoder` as I can only see this being worthwhile if you have access to the low level shared buffers of the HTTP server library.

**Comment by jknack** [comment]
The buffer feature is the one that hold me from releasing final 3.0.

I will probably do the release and introduce the buffer feature in less say 3.1

> low level shared buffers of the HTTP server library.

I'm looking into this the one that are going to benefit are Netty/Undertow, but of course not on a simple/single "hello world" test. Buffer will benefit encoder in general, but not single/static payload (ByteBuffer.wrap())

> low level shared buffers of the HTTP server library.

In Jetty for example, this helps with performance... but will also break existing functionality on the given use case:

1. choose outputstream/writer from server (jetty or undertow)
2. something went wrong while encoding response
3. error response won't be able to render output bc of 1) and 2)

Today, do all the encoding thing occurs in memory... the server shared buffers are not affected and we always produce an errored response (with some exceptions)

**Comment by jknack** [comment]
> The only time I saw pre-encoding run faster was in Techempower and threadlocal buffers were in play

Oh and now that I remember... this was the only way I found to run fast on techempower (thread-local buffer)

**Comment by agentgt** [comment]
What I will do is add the pre-encoding option into JStachio as an experimental flag.

I will try the Techempower benchmarks with Jooby 3.0.0 with JStachio (snapshot) and see if pre-encoding wins. Then I will let you see the branch/pr of the techempower benchmarks so that you can run it w on your end to confirm it runs faster than the original Rocker Fortune code. Regardless I will probably use threadlocals inside the JStachio jooby module that will be configurable similar to Rocker (for now).


Meanwhile I will release JStachio 1.0.0 with the pre-encoding as an experimental option.

**Comment by agentgt** [comment]
@jknack I did some more testing on v0.16.0 of JStachio with techempower.

Your ByteBufferOutput Rocker Output seems to be fast.

0.16.0 you can use an analog of that via an OutputStream.

https://jstach.io/jstachio/io.jstach.jstachio/io/jstach/jstachio/Template.EncodedTemplate.html

I basically [just copied it](https://github.com/jooby-project/jooby/blob/3.x/modules/jooby-rocker/src/main/java/io/jooby/rocker/ByteBufferOutput.java) and made it implement OutputStream.

In JMH benchmarks JStachio performs better than Rocker but via Techempower it seems to not matter once you turn on pre-encoding. 

Even the generated code by Rocker, and JStachio look almost the same.

I still haven't tried JTE's [jte-runtime/src/main/java/gg/jte/output/Utf8ByteOutput.java](https://github.com/casid/jte/blob/main/jte-runtime/src/main/java/gg/jte/output/Utf8ByteOutput.java).

But since we turn everything into a byte array or wrap bytebuffer that still gets copied it probably will have no improvement.
