### ISSUE TITLE
Support java.util.stream.Stream for list sections

### ISSUE THREAD

**Issue by agentgt** [jstachio/jstachio#13]
Support java.util.stream.Stream for sections.

Probably should only support it for method calls as the method call essentially acts like a factory (e.g. like Iterable is to Iterator) since Streams or more like iterators then iterables.

**Comment by sviperll** [comment]
> Probably should only support it for method calls as the method call essentially acts like a factory (e.g. like Iterable is to Iterator) since Streams or more like iterators then iterables.

+1 for these analysis

**Comment by agentgt** [comment]
A custom JStacheLambda is a better solution for thiss.
