### ISSUE TITLE
Add security policy

### ISSUE THREAD

**Issue by casid** [jstachio/jstachio#155]
I believe I found a vulnerability in JStachio and would like to report it privately, so that it is not disclosed until you released a patch for it. Maybe you could add a security policy to the project (https://github.com/jstachio/jstachio/security)?

When looking into it, I just noticed there is a new Github Feature called Security Advisories, which sounds really neat: Privately discuss, fix, and publish information about security vulnerabilities in your repository's code.

**Comment by agentgt** [comment]
Oh no! 

Thank for the find!

I just saw some projects add the new security feature and forgot to put it on my TODO list.

I will be curious what it is as I imagine it is probably something to do with files being read from the annotation processor or the tiny bit of reflection in the runtime (ignoring jmustache).

BTW while I have you I was going to file a bug that JTE does not have reproducible builds from what I can tell. Build plugins and annotation processors ideally should be reproducible.

**Comment by agentgt** [comment]
I'm going to close the issue. You can file it through the standard github process.

Again thanks for the find @casid !

**Comment by agentgt** [comment]
@casid when you get a chance let me know if you can see the security issue as I’m not sure if I did it right.

BTW if it is about escaping HTML we can discuss but I can’t do context sensitive escaping and attribute escaping is a known issue in all Mustache implementations.
