### ISSUE TITLE
JStachioModelViewConfigurer config method signatuer declares Map<String, ?> insted of Map<String, Object>

### ISSUE THREAD

**Issue by frantello** [jstachio/jstachio#248]
Hello,

![imagen](https://github.com/jstachio/jstachio/assets/6098478/519abc75-0d71-4a6f-9d0b-e7bf29d711b1)

No way to add an attribute to the Spring model using JStachioModelViewConfigurer, config method signature declares model like Map<String, ?> instead of Map<String, Object>

The compiler throws error: incompatible types: String cannot be converted to CAP#1

Thanks for your support!

**Comment by frantello** [comment]
It works fine with this workaround, but it's no so elegant.

![imagen](https://github.com/jstachio/jstachio/assets/6098478/2bb0f615-35f6-417e-9968-b42b19e57217)

**Comment by agentgt** [comment]
Well that is embarrassing.

I will get that fixed right away.
