### ISSUE TITLE
Gradle compileJava inputs do not include templates

### ISSUE THREAD

**Issue by jskov** [jstachio/jstachio#257]
I just noticed that when I tweak a template file, the corresponding `compileJava` task is still UP-TO-DATE.

To work around that, I added:

```gradle
tasks.withType(JavaCompile).configureEach {
    inputs.dir("src/main/resources/templates")
}
```

And now, when I tweak a template file, the `compileTask` is executed correctly.

I seem to remember some Gradle magic that allows an APT to tell Gradle about such inputs (incremental compilation?)

I am not sure if that is what is implied with [jstache.incremental](https://jstach.io/doc/jstachio/current/apidocs/#gradle_incremental)? In any event, this option does not seem to make a difference (for this issue).

Not sure if this is a bug as such. Feature request, perhaps (if technically possible).
Maybe add the stanza (adjusted for path) to the docs?
Maybe the average Gradle buildfile writer would have cached this earlier, and I just missed it because I mostly build from Eclipse?
I am very happy to let you decide whichever :)

**Comment by agentgt** [comment]
@jskov I'm largely gradle ignorant but does this not work well or are you already using it: https://jstach.io/jstachio/#gradle_cache

```
    annotationProcessor fileTree(layout.projectDirectory.dir('src/main/resources/views')) { include '**/*' }
```

**Comment by jskov** [comment]
No, I actually did *not* see that. My bad.

I was not aware of that syntax. And cannot find anything in the Gradle docs to that effect.

But that does not matter much, as it *does* seem to work. At least as far as my testing goes.

Did you find it in a Gradle discussion? I am just curious; it does not matter much if you cannot remember.

**Comment by agentgt** [comment]
It was @hrstoyanov fantastic contribution! #200
