### ISSUE TITLE
Javaspring formatter - OK for a PR that has the results of spring-javaformat:apply in it?

### ISSUE THREAD

**Issue by karianna** [jstachio/jstachio#278]
Hi there, was about to pull the trigger on a PR to update various dependencies but the latest javaspringformmater apply does change a fair few files.  Wanted to check if that was a desirable change before submitting.

**Comment by agentgt** [comment]
The latest formatter should not be merged at this time.

The plan is to merge the formatter on minor or major version like changes which is why it is so behind.

I’m not sure why your change would need the latest formatter?

**Comment by agentgt** [comment]
@karianna I had dependabot running weekly. It just ran today so hopefully everything should be up-to-date w/ the exception of the formatter.

I will look into upgrading the formatter later this week and try to minimize the code changes.
