### ISSUE TITLE
Cache results of Templates.findTemplate()

### ISSUE THREAD

**Issue by dsyer** [jstachio/jstachio#322]
I can see some comments in `Templates` that suggest it might be a planned feature. Any reason not to do it?

Background: I was scratching an itch and doing a straight throughput performance comparison between thymeleaf and jstachio, and was surprised to see that jstachio was at best comparable where I had expected much better. I looked at some flamegraphs and noticed that `Templates.findTemplate()` was being called 3-4 times per request and since there is no cache it actually seems to result in disk I/O which would explain the poor performance overall (I suppose related to `ServiceProvider` implementation details).

**Comment by agentgt** [comment]
I think findTemplate for Spring is different and it might be checking the context and or I just forgot to turn on caching for it. Let me go check.

Is this webflux?

**Comment by dsyer** [comment]
I was in WebMVC. It'll be the same probably. It's definitely calling `Templates.findTemplate()` so not sure what you mean by "different".

**Comment by agentgt** [comment]
Oh what I meant is io.jstach.jstachio.spi.JStachioTemplateFinder.cachedTemplateFinder(JStachioTemplateFinder)

is not getting called in SpringJStachio for some reason or another.

**Comment by agentgt** [comment]
Sorry I'll actually set some break points instead of guessing out my butt :) Give me half an hour.

**Comment by dsyer** [comment]
I can save you some time then. We care calling `AbstractJStachio.write()` and `AbstractJStachio.supportsType()`. Neither is Spring specific and both require at least one call to `Templates.findTemplate()` (with no cache).

**Comment by agentgt** [comment]
No don't worry. I can see how it is not using the cached template finder.

**Comment by agentgt** [comment]
Can you put a break point on supportsType in CompositeTemplateFinder. It is io.jstach.jstachio.spi.JStachioTemplateFinder.

Then hover your mouse or however VS Code does on the `private final Iterable<? extends JStachioTemplateFinder> finders;`

![Screen Shot 2024-02-29 at 1 12 39 PM](https://github.com/jstachio/jstachio/assets/567706/806bf654-c36c-45f9-b9df-62c25bcd4be2)

Do you see any ClassCache ones in there? Yes I need to combine the composites.

**Comment by dsyer** [comment]
I see the same as you.

**Comment by dsyer** [comment]
The caching template finder is erroring out with `TemplateNotFoundException` so it always misses. There clearly *is* a template though because the app works.

**Comment by agentgt** [comment]
I can't reproduce it with the spring-webmvc example app because it finds all the templates through the application context.

Is this in the petclinic one? Can you give me a link to that project?

**Comment by agentgt** [comment]
I think what the problem is JStachioConfiguration templateFinder

```java
	@Bean
	@ConditionalOnMissingBean(JStachioTemplateFinder.class)
	public JStachioTemplateFinder templateFinder(JStachioConfig config, TemplateConfig templateConfig) {
		var templates = templatesByServiceLoader(templateConfig);
		var springTemplateFinder = JStachioTemplateFinder.cachedTemplateFinder(JStachioTemplateFinder.of(templates, 0));
		var fallbackFinder = JStachioTemplateFinder.defaultTemplateFinder(config);
		return JStachioTemplateFinder.of(List.of(springTemplateFinder, fallbackFinder));
	}
```

You are not get getting any templates by the service loader probably because of some modular problem or the META-INF services didn't get generated.


What probably needs to happen is 

```
var fallbackFinder = JStachioTemplateFinder.defaultTemplateFinder(config);
```

should be cached and there was some reason I was hesitant to do that.

I'm going to put it in the main branch to cache it along with the flattening of composite. Then I will do a maven central SNAPSHOT deploy for convenience. Sound good?

**Comment by agentgt** [comment]
@dsyer 1.4.0-SNAPSHOT is in Maven central snapshot repo. Or you can build it. Try that one out.

**Comment by dsyer** [comment]
I don't see it yet at https://oss.sonatype.org/content/repositories/snapshots/io/. I'll try again tomorrow.

**Comment by agentgt** [comment]
I don't think it is that one but this one: https://s01.oss.sonatype.org/content/repositories/snapshots/

They recently started putting projects on that one annoyingly.

**Comment by dsyer** [comment]
Sigh. Haven't they heard of virtual hosts?

**Comment by dsyer** [comment]
There's a trivial fix for this specific bottleneck in `ViewResolvingHanderlInterceptor` (it has no need to check for `JStachio.supportsType()` if it already has a `View`:

```java
	public void postHandle(HttpServletRequest request, HttpServletResponse response, Object handler,
			ModelAndView modelAndView) throws Exception {

		if (modelAndView == null || modelAndView.getView() != null || !HandlerMethod.class.isInstance(handler)) {
			return;
		}
		...
```

It's a trivial change so I won't bother with a pull request unless you ask. It squeezes another 2x performance out of a simple sample where the `@Controller` method returns `JStachioModelView`.

Whether or not `JStachio.supportsType()` can be cached or short-cutted in some other way, I leave up to you.

**Comment by agentgt** [comment]
It is a bug for sure with the cache. I will have a fix shortly. The reason I never noticed it on my end is because `supportTypes` was always given types that are JStache. What is happening is the supportsType is calling the template finder and the default one is throwing an exception for the types that are not found.

Furthermore going back to the code I modified I now realize why I didn't cache the fallbackFinder:


```
	@Bean
	@ConditionalOnMissingBean(JStachioTemplateFinder.class)
	public JStachioTemplateFinder templateFinder(JStachioConfig config, TemplateConfig templateConfig) {
		var templates = templatesByServiceLoader(templateConfig);
		var springTemplateFinder = JStachioTemplateFinder.cachedTemplateFinder(JStachioTemplateFinder.of(templates, 0));
		var fallbackFinder = JStachioTemplateFinder.defaultTemplateFinder(config);
		return JStachioTemplateFinder.of(List.of(springTemplateFinder, fallbackFinder));
	}
```

The reason is it should never be used in a production environment and is just there for hot reload and similar.  That is `templates` should not have been empty however that still doesn't fix the supportType not caching correctly.

I'll have an updated SNAPSHOT soon. Its great find Dave! And given the libraries touted performance it is embarrassing I didn't spot it earlier but I guess I was always passing types `supportedType` knows about.

**Comment by agentgt** [comment]
@dsyer I think I fixed it. Try the latest SNAPSHOT and if you don't mind reviewing the previous commits associated with this bug.

I can't thank you enough on finding this bug!

Once you check it out I will do a release.

**Comment by dsyer** [comment]
That seems to fix it. I'm only getting 2.5x better throughput than Thymeleaf, and I was hoping for 3x at least, but I can't see any further optimizations in the flame graphs.

**Comment by agentgt** [comment]
I'm amazed it is even 2.5x (I assume we are talking about the entire request) although I think that is probably more indicative of how slow Thymeleaf is and not how fast JStachio is.

That is template rendering should be a small subset of the total cost of serving the request for Spring MVC so I imagine faster engines like JMustache even though it uses reflection will be pretty close to JStachio.

I still am concerned why your templates were not found by the service loader as a full production build should cause the annotation processor to generate a service loader registration. How were you running the benchmark?


Also for others. You can always wire in templates aka renderers or use them directly which avoids the lookup.

That is you can return a TemplateModel.


```java
public TemplateModel someRequestMapping() {
  return SomeRender.of().model(model);
}
```
