### ISSUE TITLE
FYI 0.8.1 causes infinite loop in Gradle compilation

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jstachio/jstachio#36]
And 0.7.0 and 0.8.0 before it.

Regrettably, I have not had time to investigate, if this is because something I have failed to fix - a requirement for updating from 0.8

But I thought I would notify you, before you suddenly release 1.0 with (maybe?) problems in the Gradle plugin.

I hope I will have time to dig into it this weekend.

You can see the dependabot result on my project here:
https://github.com/jskov/openapi-jaxrs-client/actions/runs/3639636836/jobs/6143271240

**Comment by agentgt** [comment]
The package changed from:

io.jstach.annotation
to
io.jstach.jstache

sorry there won’t be anymore package changes especially after 1.0.

**Comment by jskov** [comment]
No problem, I did not look into it properly. Was just surprised that it made Gradle explode like that.

I experience a couple of other problems, though. Will create separate issues.

**Comment by jskov** [comment]
Never mind, bad build file. My projects runs with 0.8.1 now. Cheers!
