### ISSUE TITLE
Updating to 0.9.0 causes APT problems for both Eclipse and Gradle

### ISSUE THREAD

**Issue by jskov** [jstachio/jstachio#48]
Both report

    Note: no existing services file found

This is all there is in Eclipse's error log.

Gradle says the same, but only after not being able to find template files in "build/classes/java/main" which is empty at the time the plugin fails.

You can have a try with my project: https://github.com/jskov/openapi-jaxrs-client
(bump the version in gradle.properties and run `./gradlew jar`)

Cheers!

**Comment by agentgt** [comment]
Sorry about that. I see what I messed up when trying to make the incremental configurable and forgot to go test gradle before release.

I might just fork your project and have it get kicked off on every build 👍

**Comment by agentgt** [comment]
I know for sure the bug is there as I have seen it before but can't seem to reproduce it for 0.9.0. Regardless I can clearly see why it is happening so I'll put the fix in.

**Comment by agentgt** [comment]
@jskov I think it is fixed now and released v0.9.1 . Can you please test as I can't seem to get my Eclipse to fail on the incremental for gradle.

**Comment by jskov** [comment]
Yes. 0.9.1 works. Thanks so much!

**Comment by jskov** [comment]
Also in eclipse, btw
