### ISSUE TITLE
JStache.template() -> JStache.inline() refactor

### ISSUE THREAD

**Issue by agentgt** [jstachio/jstachio#53]
The JStache annotation attribute `template` is confusing as it is unclear if it is the path or a string literal.

Thus:

```java
JStache(template="{{message}}")
```

Will become:

```java
JStache(inline="{{message}}")
```

**Comment by sviperll** [comment]
I've though that these maybe should be two different annotations....

````
@JStacheInline(template="{{message}}")
````

and

````
@JStacheExternal(path="my.mustache")
````
