### ISSUE TITLE
JStachioModelView should override getContentType()

### ISSUE THREAD

**Issue by dsyer** [jstachio/jstachio#67]
`JStachioModelView` helpfully provides a `contentType()` method that sort of hides the `getContentType()` from the super type - at least from idiots like me. Wouldn't it be better to actually rename the existing method to be the same as the supertype, or at least provide a default implementation that is the same?

**Comment by agentgt** [comment]
Yeah I can't remember why I did that. Sorry about that.

I have been lately not doing getter/setters as Java has been kind of moving in that direction because of Records so maybe that is why I accidentally did that.

I will correct it today or tomorrow.
