### ISSUE TITLE
Parent blocks do not allow other partials in blocks

### ISSUE THREAD

**Issue by agentgt** [jstachio/jstachio#71]
Parent blocks e.g. `{{< someparent}}` do not allow partials (parent or regular) inside blocks `{{$block}}{{> somepartial}}{{/blocks}}`

I accidentally pre-merged #68 (sorry @dsyer ).

**Comment by dsyer** [comment]
FWIW I worked around it using a lambda that explicitly rendered its context. It would be nice to have this working though.

**Comment by dsyer** [comment]
Could you find some time to help me OOB maybe? I don't understand why some things don't work still.

**Comment by agentgt** [comment]
Sure. Today might be tough as my son still has school vacation but next week I should be available.

**Comment by dsyer** [comment]
Drop me a line with an email address or something.

**Comment by agentgt** [comment]
dev a_t_ adamgent _ com

Replace the a_t_ with at symbol and other underscore with dot.

This coming Monday works better for me.

**Comment by agentgt** [comment]
@dsyer Fixed. Damn I really need to rewrite the compiler. The single pass push nature is painful to make changes with.

The good news is now jstachio is fully compliant with non optional parts of the mustache spec.

@jgonggrijp wontache playground was quite helpful in making sure I got the spacing right on the inheritance.
