### ISSUE TITLE
Illegal start of type with wildcard generics

### ISSUE THREAD

**Issue by Allsimon** [jstachio/jstachio#88]
With `0.10.1`, template like this will not compile:

```java
@JStache(template = """
        {{#options}}
        {{#transform}}
        {{name}}
        {{/transform}}
        {{/options}}""")
public record FooGen(List<GenericRecord<?>> options) {
    record GenericRecord<T>(T value) {
    }

    @JStacheLambda
    public CRecord transform(GenericRecord<?> option) {
        return new CRecord("repro");
    }

    record CRecord(String name) {
    }
}
```

The generated code in `render(...)`:
```java
...
        for (java.util.Iterator<? extends FooGen.GenericRecord<>> elementIt = data.options().iterator(); elementIt.hasNext(); i++) {
            FooGen.GenericRecord<> element = elementIt.next();
        if (element != null) { 
...
```
the wildcard is missing so the code doesn't compile

---

If we remove the wildcard like this
```diff
-public record FooGen(List<GenericRecord<?>> options) {
+public record FooGen(List<GenericRecord> options) {
```

or specify the type, the code will compile
```diff
-public record FooGen(List<GenericRecord<?>> options) {
+public record FooGen(List<GenericRecord<String>> options) {
```

**Comment by agentgt** [comment]
Thank you so much for find this issue.

Yeah I can't believe I forgot about the wild card issue. I knew this was issue a long time ago back when I inherited static-mustache but just forgot to revisit it (and file a bug apparently). 

I'll have fix in sometime today or tomorrow.

Oddly enough I was working on a fix of it with the nullable annotations #4 on a different branch but ran into some other non related issues.
